#!/bin/sh
#
# Photos - access, organize and share your photos on GNOME
# Copyright © 2012 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#


[[ "$1" = "--header" ]] &&
    echo "#ifndef PHOTOS_ABOUT_DATA_H" &&
    echo "#define PHOTOS_ABOUT_DATA_H" &&
    echo "#include <glib.h>" &&
    echo "G_BEGIN_DECLS" &&
    echo "extern const gchar *PHOTOS_ARTISTS[];" &&
    echo "extern const gchar *PHOTOS_AUTHORS[];" &&
    echo "G_END_DECLS" &&
    echo "#endif" &&
    exit

echo "const gchar *PHOTOS_ARTISTS[] = {"
while read line; do
    [[ $(echo "$line" | cut -c1) = "#" ]] &&
        continue
    [[ ${#line} -eq 0 ]] &&
        continue
    echo "  \"$line\","
done < $2/ARTISTS
echo "  NULL"
echo "};"

echo "const gchar *PHOTOS_AUTHORS[] = {"
while read line; do
    [[ $(echo "$line" | cut -c1) = "#" ]] &&
        continue
    [[ ${#line} -eq 0 ]] &&
        continue
    echo "  \"$line\","
done < $2/AUTHORS
echo "  NULL"
echo "};"
